import Head from "next/head";
import s from "@styles/Home.module.css";
import { Navbar } from "@components/Navbar";
import { Loader } from "@components/Loader";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./light.ico" />
      </Head>

      <main className={s.main}>
        <Navbar />
        <Loader />
      </main>
    </>
  );
}
