import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="./light.ico" rel="icon" />
      </Head>
    </>
  );
}
